# No ports are exposed by default because tests run concurrently on a single CI instance
version: '3.5'

services:
  cassandra:
    image: cassandra:3.11
    logging:
      driver: none
    # ports:
    #   - '9042:9042'

  temporal:
    image: temporalio/auto-setup:1.12.1
    # ports:
    #   - '7233:7233'
    #   - '7234:7234'
    #   - '7235:7235'
    #   - '7239:7239'
    #   - '6933:6933'
    #   - '6934:6934'
    #   - '6935:6935'
    #   - '6939:6939'
    environment:
      - 'CASSANDRA_SEEDS=cassandra'
      - 'DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml'
    depends_on:
      - cassandra

  temporal-web:
    image: temporalio/web:1.11.0
    logging:
      driver: none
    # ports:
    #   - '8088:8088'
    environment:
      - 'TEMPORAL_GRPC_ENDPOINT=temporal:7233'
    depends_on:
      - temporal
